# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vbguest.auto_update = false

  # --- Máquina WEB ---
  config.vm.define "webserver-lb4" do |web_config|
    web_config.vm.box = "ubuntu/trusty64"
    web_config.vm.hostname = "webserver"
    web_config.vm.network "private_network", ip: "192.168.56.21"
    web_config.vm.network "forwarded_port", guest: 80, host: 8080

    web_config.vm.provider "virtualbox" do |vb|
      vb.name = "webserver-lb4"
      opts = ["modifyvm", :id, "--natdnshostresolver1", "on"]
       vb.customize opts
       vb.memory = "256"
     end
    web_config.vm.provision 'shell', path: "bootstrap_web.sh"
  end

  # --- Máquina CLIENT ---
  config.vm.define "client-lb4" do |client_config|
    client_config.vm.box = "ubuntu/trusty64"
    client_config.vm.hostname = "client"
    client_config.vm.network "private_network", ip: "192.168.56.22"

    client_config.vm.provider "virtualbox" do |vb|
      vb.name = "client-lb4"
      vb.memory = 256
      vb.cpus = 1
    end

    #  LINHA ADICIONADA PARA O LAB 4:
    client_config.vm.provision "shell", path: "bootstrap-client.sh"
  end
end
